'use strict';

const express = require('express');
const pino = require('pino');
const client = require('prom-client');

const PORT = process.env.PORT || 3000;
const SERVICE_NAME = process.env.SERVICE_NAME || 'observability-app';

// ---------------------------------------------------------------------------
// Structured JSON logger (pino)
//
// Every log line is a single JSON object written to stdout with the fields:
//   timestamp, level, service, method, path, statusCode, message
// Docker's gelf logging driver ships each stdout line to Logstash.
// ---------------------------------------------------------------------------
const logger = pino({
  base: { service: SERVICE_NAME },
  messageKey: 'message',
  // Emit an ISO-8601 "timestamp" field instead of pino's default epoch "time".
  timestamp: () => `,"timestamp":"${new Date().toISOString()}"`,
  // Emit the level as a human-readable label ("info", "warn", "error").
  formatters: {
    level(label) {
      return { level: label };
    },
  },
});

// ---------------------------------------------------------------------------
// Prometheus metrics (prom-client)
// ---------------------------------------------------------------------------
const register = new client.Registry();
register.setDefaultLabels({ service: SERVICE_NAME });

// Default Node.js process / runtime metrics (CPU, memory, event loop, ...).
client.collectDefaultMetrics({ register });

// Custom counter: total number of HTTP requests handled.
const requestsTotal = new client.Counter({
  name: 'app_requests_total',
  help: 'Total number of HTTP requests received by the application',
  labelNames: ['method', 'path', 'status_code'],
  registers: [register],
});

// Custom counter: total number of application errors.
const errorsTotal = new client.Counter({
  name: 'app_errors_total',
  help: 'Total number of errors generated by the application',
  labelNames: ['path'],
  registers: [register],
});

const app = express();

// ---------------------------------------------------------------------------
// Request middleware: count every request and log it as JSON once finished.
// ---------------------------------------------------------------------------
app.use((req, res, next) => {
  res.on('finish', () => {
    requestsTotal.inc({
      method: req.method,
      path: req.path,
      status_code: res.statusCode,
    });

    const level =
      res.statusCode >= 500 ? 'error' : res.statusCode >= 400 ? 'warn' : 'info';

    logger[level](
      {
        method: req.method,
        path: req.originalUrl,
        statusCode: res.statusCode,
      },
      'request handled'
    );
  });
  next();
});

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------
app.get('/', (req, res) => {
  res.json({
    message: 'Hello from the DevOps Observability Lab',
    service: SERVICE_NAME,
  });
});

app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

// Deliberately fails so we can drive the error rate up for the alert demo.
app.get('/error', (req, res) => {
  errorsTotal.inc({ path: '/error' });
  res.status(500).json({ error: 'Simulated application error' });
});

// Prometheus scrape endpoint.
app.get('/metrics', async (req, res) => {
  res.set('Content-Type', register.contentType);
  res.end(await register.metrics());
});

// ---------------------------------------------------------------------------
// Catch-all error handler: also counts unexpected failures as app errors.
// ---------------------------------------------------------------------------
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  errorsTotal.inc({ path: req.path });
  logger.error(
    {
      method: req.method,
      path: req.originalUrl,
      statusCode: 500,
      message: err.message,
    },
    'unhandled application error'
  );
  res.status(500).json({ error: 'Internal Server Error' });
});

app.listen(PORT, () => {
  logger.info({ port: PORT }, `application started on port ${PORT}`);
});
