{
 "title": "Observability App Dashboard",
 "tags": [
  "observability",
  "lab"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests (app_requests_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "app_requests_total",
     "legendFormat": "{{method}} {{path}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "Total Errors (app_errors_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_errors_total", "legendFormat": "errors {{path}}" }
   ]
  },
  {
   "title": "Request Rate - rate(app_requests_total[1m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Error Rate - rate(app_errors_total[1m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(app_errors_total[1m]))",
     "legendFormat": "errors/sec"
    }
   ]
  }
 ]
}